spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: session-service-ws
              uri: lb:ws://session-service
              predicates:
                - Path=/ws/**
            - id: session-service-http
              uri: lb://session-service
              predicates:
                - Path=/sessions/**
            - id: session-service-ui
              uri: lb://session-service
              predicates:
                - Path=/**
            - id: game-engine
              uri: lb://game-engine
              predicates:
                - Path=/games/**