spring:
  application:
    name: session-service

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

game-engine:
  url: http://game-engine

simulation:
  move-delay: 700ms